### ISSUE TITLE
TypeError: undefined is not an object in TemplateRunTab

### ISSUE THREAD

**Issue by kreinhard** [kreinhard/merlin#21]
After click on any template card:

TypeError: undefined is not an object (evaluating 'Object.keys(_this.props.runConfigurations[_this.props.primaryKey])')
TemplateRunTab
src/components/views/templates/TemplateRunTab.jsx:82
  79 |     super(props);
  80 | 
  81 | 
> 82 |     Object.keys(this.props.runConfigurations[this.props.primaryKey])
     | ^  83 |         .filter(key => this.runConfiguration[key] !== undefined)
  84 |         .forEach(key => this.runConfiguration[key] = this.props.runConfigurations[this.props.primaryKey][key]);
  85 | }
View compiled

**Comment by finreinhard** [comment]
fixed in 81dd6a2
